version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_DATABASE:-lottery}
      MYSQL_USER: ${DB_USERNAME:-lotteryuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-lottery_pass}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: lottery-app:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - appnet
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  node_builder:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    image: lottery-node-builder:latest
    networks:
      - appnet

  web:
    image: nginx:1.24
    depends_on:
      - app
    volumes:
      - ./:/var/www:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # certs from host
    ports:
      - "80:80"
      - "443:443"
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet: