<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Report Storage Path
    |--------------------------------------------------------------------------
    |
    | Directory where generated PDF reports will be stored
    |
    */
    'storage_path' => 'reports',

    /*
    |--------------------------------------------------------------------------
    | Supported Languages
    |--------------------------------------------------------------------------
    |
    | Languages available for report generation
    |
    */
    'languages' => ['en', 'si', 'ta'],

    /*
    |--------------------------------------------------------------------------
    | DomPDF Options
    |--------------------------------------------------------------------------
    |
    | Configuration for DomPDF library
    |
    */
    'pdf_options' => [
        'enable_html5_parser' => true,
        'enable_remote' => true,
        'default_font' => 'DejaVu Sans',
        'paper' => 'a4',
        'orientation' => 'portrait',
        'enable_unicode' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Report Labels (Multi-language)
    |--------------------------------------------------------------------------
    |
    | Translations for report content
    |
    */
    'labels' => [
        'en' => [
            'title' => 'Lottery Draw Report',
            'draw_number' => 'Draw Number',
            'draw_date' => 'Draw Date',
            'winning_numbers' => 'Winning Numbers',
            'bonus_number' => 'Bonus Number',
            'prize_breakdown' => 'Prize Breakdown',
            'category' => 'Category',
            'winners' => 'Winners',
            'prize_per_winner' => 'Prize per Winner',
            'total_sales' => 'Total Sales',
            'jackpot' => 'Jackpot Amount',
            'agent_info' => 'Agent Information',
            'agent_name' => 'Agent Name',
            'agent_code' => 'Agent Code',
            'generated_on' => 'Generated on',
            'generated_by' => 'Generated by',
        ],
        'si' => [
            'title' => 'ලොතරැයි දිනුම් වාර්තාව',
            'draw_number' => 'දිනුම් අංකය',
            'draw_date' => 'දිනුම් දිනය',
            'winning_numbers' => 'ජයග්‍රාහී අංක',
            'bonus_number' => 'ප්‍රසාද අංකය',
            'prize_breakdown' => 'ත්‍යාග බෙදීම',
            'category' => 'කාණ්ඩය',
            'winners' => 'ජයග්‍රාහකයින්',
            'prize_per_winner' => 'එක් ජයග්‍රාහකයෙකුට ත්‍යාගය',
            'total_sales' => 'මුළු විකුණුම්',
            'jackpot' => 'ජැක්පොට් මුදල',
            'agent_info' => 'නියෝජිත තොරතුරු',
            'agent_name' => 'නියෝජිත නම',
            'agent_code' => 'නියෝජිත කේතය',
            'generated_on' => 'ජනනය කළ දිනය',
            'generated_by' => 'ජනනය කළේ',
        ],
        'ta' => [
            'title' => 'லாட்டரி டிரா அறிக்கை',
            'draw_number' => 'டிரா எண்',
            'draw_date' => 'டிரா தேதி',
            'winning_numbers' => 'வெற்றி எண்கள்',
            'bonus_number' => 'போனஸ் எண்',
            'prize_breakdown' => 'பரிசு விவரங்கள்',
            'category' => 'வகை',
            'winners' => 'வெற்றியாளர்கள்',
            'prize_per_winner' => 'ஒரு வெற்றியாளருக்கு பரிசு',
            'total_sales' => 'மொத்த விற்பனை',
            'jackpot' => 'ஜாக்பாட் தொகை',
            'agent_info' => 'ஏஜென்ட் தகவல்',
            'agent_name' => 'ஏஜென்ட் பெயர்',
            'agent_code' => 'ஏஜென்ட் குறியீடு',
            'generated_on' => 'உருவாக்கப்பட்ட தேதி',
            'generated_by' => 'உருவாக்கியவர்',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Lottery Logo Mapping
    |--------------------------------------------------------------------------
    |
    | Map lottery codes to logo filenames
    |
    */
    'logos' => [
        'AK' => 'ada-kotipathi.png',
        'DS' => 'supiridana.png',
        'JS' => 'jayoda.png',
        'KP' => 'kp.png',
        'LW' => 'lagna-wasanawa.png',
        'SB' => 'shanida.png',
        'SF' => 'sc.png',
        'SR' => 'supiri-dhana-sampatha.png',
    ],
];
